[[file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]

* P’undrak’s STL

This is my very own partial, sketchy, weird and ineffective STL implementation, mainly focused on the containers of the actual Standard Template Library. You have absolutely no other reason to look at this source code than being a student like myself seeking for hints on how to do things. Spoiler: what you will see here is probably not the right way to do it, but hey, it works!... sometimes. I also try to stay as close as possible to the C++17 standard. I might not always follow it though.

Developped under Spacemacs, compiled with Clang++, debugged with GDB, drinking milk. Yeah, I don’t like coffee. Milk though...

Also, don’t pay any attention to [[https://github.com/Phundrak/PhundrakSTL/blob/master/src/test.cc][src/test.cc]], it is just me testing my STL and fooling around with it.

* Installation

Haha, good joke!

Seriously, if you want to use it, just download the header files, place them in your include directory in your project, and add them with ~#include "vector.hh"~ or something like that. But honestly, use it only for testing purposes, or looking at how I did things, but not for actual work. That would be a terrible idea.

* Licence

See the LICENCE.md file, basically you are free to do whatever you want with my source code, from copying, to modifying and redistributing it, as long as it stays under the GNU GPLv3 licence.

* Bugs

Yep, there are bugs. I may or may not fix them, it’s up to me.

Also, Github doesn’t seem to fully recognize org-mode’s syntax. Well...
